[package]
name = "minigame-agar-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
rand = "0.9.1"
rand_chacha = "0.9.0"
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
tokio = { version = "1.44.2", features = ["full"] }
warp = "0.3.7"
